### ISSUE TITLE
Usar la libreria FAISS para manejar dimensionalidad alta

### ISSUE THREAD

**Issue by MatiasMaravi** [MatiasMaravi/BD2-Project2#36]
Correcto uso y aplicacion de indices para vectores de alta dimension (FAISS): +1 en la PC03
https://engineering.fb.com/2017/03/29/data-infrastructure/faiss-a-library-for-efficient-similarity-search/

**Comment by AlejandroCalizaya** [comment]
Completado, todo está en mi rama.
